#!/bin/sh

regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo Your email $email fulfills the git policy, commit successful!
    exit 0
else
    echo Your email $email doesnt fulfill the policy, no commit
    exit 1
fi